version: "3.8"
services:
  backend:
    build: ../backend
    container_name: promptdna_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=promptdna
      - FORWARDER=mock
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: promptdna_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ../frontend
    container_name: promptdna_frontend
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

volumes:
  mongo_data:
